version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    hostname: jenkins
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '1'
          memory: 2048M         
    environment:
    - JAVA_OPTS: ${JAVA_OPTS}
    - JENKINS_USER: ${JENKINS_USER}
    - JENKINS_PASS: ${JENKINS_PASS}
    volumes:
    - nfs_jenkins_app:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - frontend   

volumes:
  nfs_jenkins_app:    
    
networks:
  frontend:    
    
